import type { Metadata } from "next";
import "./globals.css";
import hljs from 'highlight.js';
import 'highlight.js/styles/dark.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="border-emerald-50 border-[1px]">
          {children}
      </body>
    </html>
  );
}
